### PR TITLE
Fix discovery with absolute paths

### LINKED ISSUE #89: `cabal-gild-1.3.2` breaks `discover src`
Not sure what's going on, but an index-state bump allowed HLS to pull in newer `cabal-gild`, which broke our tests. I manually tracked it down to `cabal-gild-1.3.2`, so I guess https://github.com/tfausak/cabal-gild/pull/84. 

Here's what we have in the failing test, I don't know why this would have started failing now? https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-cabal-gild-plugin/test/testdata/commented_testdata.cabal#L8

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #89.

### CODE REVIEW

File: source/library/CabalGild/Unstable/Action/EvaluatePragmas.hs [hunk 1]
```diff
@@ -76,21 +76,17 @@ discover p n fls dt ds = do
...
           $ if null args then ["."] else args
-  let exclusions = List.nubOrd $ fmap (normalize . FilePath.combine root) excs
+      exclusions = List.nubOrd $ fmap normalize excs
       inclusions =
         List.nubOrd
-          . fmap (normalize . FilePath.combine root)
+          . fmap normalize
           $ if null incs then ["**"] else incs
-  files <- Trans.lift $ MonadWalk.walk "." inclusions exclusions
+  files <- Trans.lift $ MonadWalk.walk root inclusions exclusions
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Action/EvaluatePragmas.hs:89]: The basic idea of this fix is that we'll use `root` rather than the current directory to search for files. The files returned are relative to the `root`, and the inclusions and exclusions are also evaluated relative to the `root`. So everything works out nicely without having to do too much. 

Removing a lot of calls to `combine root` is a nice bonus.

File: source/test-suite/Main.hs [hunk 2]
```diff
@@ -1544,8 +1544,18 @@ main = Hspec.hspec . Hspec.parallel . Hspec.describe "cabal-gild" $ do
...
+      readFile "r.cabal"
+        `Hspec.shouldReturn` unlines
+          [ "library",
+            "  -- cabal-gild: discover --exclude=.\\M2.hs --exclude=N/M1.hs",
+            "  exposed-modules:",
+            "    M1",
+            "    N.M2"
+          ]
+      d <- Directory.getCurrentDirectory
+      Gild.mainWith ["--input", FilePath.combine d "i.cabal", "--output=r.cabal"]
```
Comment (tfausak) [inline source/test-suite/Main.hs]: I originally had a pure test for this, but I think it makes more sense to test using the real file system. Windows paths are weird, and using the actual filesystem exercises the functionality without jumping through a bunch of hoops.
