### PR TITLE
Fix extension sorting

### LINKED ISSUE #29: Default-extensions get randomly sorted
I got the following diff after running cabal-gild:

```diff 
 common base-settings
   default-extensions:
-    NoImplicitPrelude
-    NoMonomorphismRestriction
-    BangPatterns
-    BlockArguments
-    ConstraintKinds
-    DataKinds
-    DefaultSignatures
-    DeriveDataTypeable
-    DeriveFoldable
-    DeriveFunctor
-    DeriveGeneric
-    DeriveTraversable
-    DerivingVia
-    EmptyDataDecls
+    ParallelListComp
+    MultiParamTypeClasses
+    FunctionalDependencies
+    RankNTypes
+    ScopedTypeVariables
     FlexibleContexts
     FlexibleInstances
-    FunctionalDependencies
-    GADTs
+    EmptyDataDecls
+    BangPatterns
+    TemplateHaskell
+    PatternGuards
     GeneralizedNewtypeDeriving
-    InstanceSigs
-    LambdaCase
-    LiberalTypeSynonyms
     MagicHash
-    MultiParamTypeClasses
-    MultiWayIf
-    NumericUnderscores
+    TypeFamilies
+    StandaloneDeriving
+    LiberalTypeSynonyms
+    TypeOperators
+    RecordWildCards
     OverloadedStrings
-    ParallelListComp
-    PatternGuards
+    GADTs
+    UnboxedTuples
+    DeriveDataTypeable
+    DeriveGeneric
+    DefaultSignatures
+    InstanceSigs
     QuasiQuotes
-    RankNTypes
-    RecordWildCards
-    ScopedTypeVariables
-    StandaloneDeriving
-    StrictData
-    TemplateHaskell
     TupleSections
+    MultiWayIf
+    LambdaCase
+    DeriveFunctor
+    DeriveTraversable
+    DeriveFoldable
+    ConstraintKinds
+    DataKinds
+    StrictData
     TypeApplications
-    TypeFamilies
-    TypeOperators
-    UnboxedTuples
+    DerivingVia
+    BlockArguments
+    NumericUnderscores
+    NoMonomorphismRestriction
+    NoImplicitPrelude
```

Can we have a natural sorting there?

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #29. 

See https://github.com/tweag/ormolu/pull/471 for similar work in Ormolu.

### CODE REVIEW

File: source/library/CabalGild/Type/Extension.hs [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+import qualified Data.Char as Char
+import qualified Data.Ord as Ord
+import qualified Distribution.Parsec as Parsec
+import qualified Distribution.Pretty as Pretty
+import qualified Language.Haskell.Extension as Extension
+
+-- | This type exists to provide a different 'Ord' instance for
+-- 'Extension.Extension'. The instance provided by @Cabal-syntax@ sorts things
+-- in a surprising order. This one sorts things alphabetically with "enable"
+-- extensions before "disable" ones.
```
Comment (tfausak) [inline source/library/CabalGild/Type/Extension.hs:12]: This comment explains the crux of this PR.
