### PR TITLE
Correctly handle all version ranges

### LINKED ISSUE #117: Some version ranges handled incorrectly
The `-any` syntax was removed in Cabal 3.4:

       expected: cabal-version: 3.4
                 build-depends: v-any-new
                 
        but got: cabal-version: 3.4
                 build-depends: v-any-new -any

Same for `-none`:

       expected: cabal-version: 3.4
                 build-depends: v-none-new <0
                 
        but got: cabal-version: 3.4
                 build-depends: v-none-new -none

Wildcards are not round tripped (these were introduced in 1.6, but adding the `cabal-version` doesn't change the behavior):

       expected: "build-depends: v-within ==1.*\n"
        but got: "build-depends: v-within >=1 && <2\n"

Neither is set notation:

       expected: cabal-version: 3.0
                 build-depends: v-set =={1, 2}
                 
        but got: cabal-version: 3.0
                 build-depends: v-set ==1 || ==2

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #117. 

This is still a draft because I need to clean up the version range module considerably. Also I need to see if there are any other places that version ranges are accepted and consider plugging in this implementation there.

### CODE REVIEW

**Comment by tfausak** [comment]
> any other places that version ranges are accepted

For example the `tested-with` field uses version ranges: https://hackage.haskell.org/package/Cabal-syntax-3.14.1.0/docs/Distribution-FieldGrammar-Newtypes.html#t:TestedWith

**Comment by tfausak** [comment]
Both `build-tool-depends` (`ExeDependency`) and `build-tools` (`LegacyExeDependency`) could benefit from these new version ranges. But I don't think it's worth the effort. I would have to re-implement both those types like I did for `tested-with`.

File: source/test-suite/Main.hs [hunk 1]
```diff
@@ -635,7 +635,12 @@ main = Hspec.hspec . Hspec.parallel . Hspec.describe "cabal-gild" $ do
     Hspec.it "formats impl without version range" $ do
       expectGilded
         "if impl ( ghc )"
-        "if impl(ghc >=0)\n"
+        "if impl(ghc)\n"
```
Comment (tfausak) [inline source/test-suite/Main.hs:638]: This changed because Cabal used to insert an implicit `anyVersion` whenever the version range was missing. Now the optionality is properly modeled.
