### PR TITLE
Change how trailing comments are formatted

### LINKED ISSUE #122: cabal-gild formatter break nix hash pragma in `cabal.project`
I discovered that the cabal-gild formatter destroys the `sha256` hash pragma in `cabal.project`.
[[Add cabal-gild, a cabal formatter by jian-lin · Pull Request #361 · numtide/treefmt-nix](https://github.com/numtide/treefmt-nix/pull/361)](https://github.com/numtide/treefmt-nix/pull/361)
I was happy to configure it since treefmt-nix now supports cabal-gild, but it enables formatting of `cabal.project` by default.
While this is actually something to be happy about, I discovered that it causes issues with nix integration.
Nix's [[input-output-hk/haskell.nix: Alternative Haskell Infrastructure for Nixpkgs](https://github.com/input-output-hk/haskell.nix)](https://github.com/input-output-hk/haskell.nix) has a mechanism to enhance reliability by specifying hashes in `cabal.project`.
You write it in `cabal.project` as follows:

```
source-repository-package
  type: git
  location: https://github.com/pz-tapioca-verandah/wasmtime-hs
  tag: 25d9be1302263b601a669c052b069361175af08c
  --sha256: 0h0k0jlx9lr6rwwvjmkvjzwamb4z5dvssr2p2jz5mxqw2r4bjygs

```

cabal-gild formats it like this:

```
source-repository-package
  type: git
  location: https://github.com/pz-tapioca-verandah/wasmtime-hs
  tag: 25d9be1302263b601a669c052b069361175af08c

--sha256: 0h0k0jlx9lr6rwwvjmkvjzwamb4z5dvssr2p2jz5mxqw2r4bjygs

```

Then nix cannot detect the hash and shows warnings like this:

```
trace: WARNING: No sha256 found for source-repository-package https://github.com/pz-tapioca-verandah/wasmtime-hs ref=(unspecified) rev=25d9be1302263b601a669c052b069361175af08c download may fail in restricted mode (hydra)
trace: Consider adding `--sha256: 0h0k0jlx9lr6rwwvjmkvjzwamb4z5dvssr2p2jz5mxqw2r4bjygs` to the cabal.project file or passing in a sha256map argument
trace: WARNING: No sha256 found for source-repository-package https://github.com/pz-tapioca-verandah/wasmtime-hs ref=(unspecified) rev=25d9be1302263b601a669c052b069361175af08c download may fail in restricted mode (hydra)
trace: Consider adding `--sha256: 0h0k0jlx9lr6rwwvjmkvjzwamb4z5dvssr2p2jz5mxqw2r4bjygs` to the cabal.project file or passing in a sha256map argument
```

I agree that "hash specification and such instructions shouldn't be done in comments."
But since I didn't decide this, there's nothing I can do about it.
I'm not even sure whether this was decided by haskell.nix or by something further upstream in Nix.
For now, it stays quiet if I add the hash, and so far this hasn't caused any problems.

Since it's just warnings, it's not a critical issue, but are there any workarounds?
Personally, I think that when indented comments are near the end of a section, they're likely related to that section, so it might be okay to preserve the indentation as is.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #122. 

Before, Gild would only associate comments downwards. Even if you had a comment at the same indentation level, it could become un-indented. For example:

``` cabal
-- input
some-section
  some-field: some value
  -- some comment
```

``` cabal
-- old output
some-section
  some-field: some value

-- some comment
```

The new output is the same as the input. It keeps the comment nested within the section. 

This is an alternative to #142. It was still mostly authored by Claude Code, but I did some refactoring first to make the diff smaller. I also added some test cases to cover the desired behavior. 

For previous attempts, see #125 and #127.

### CODE REVIEW

File: source/library/CabalGild/Unstable/Type/Comments.hs [hunk 1]
```diff
@@ -2,26 +2,25 @@
...
+    after :: [Comment.Comment p]
+  }
   deriving (Eq, Show)
 
 instance Semigroup (Comments p) where
-  xs <> ys = fromList $ Function.on (<>) toList xs ys
+  xs <> ys =
+    MkComments
+      { before = before xs <> before ys,
+        after = after xs <> after ys
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Type/Comments.hs]: This should maybe be flipped:
```suggestion
        after = after ys <> after xs
```
I should write a test with some multi-line comments to be sure.

File: source/library/CabalGild/Unstable/Action/ExtractComments.hs [hunk 2]
```diff
@@ -13,12 +12,10 @@ import qualified Distribution.Parsec.Position as Position
 
 -- | Extracts comments from the given byte string. This is a wrapper around
 -- 'fromLine', where lines are split using 'Latin1.lines'.
-fromByteString :: ByteString.ByteString -> Comments.Comments Position.Position
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Action/ExtractComments.hs:16]: This never should have returned `Comments`. I messed that up in #143.

File: source/library/CabalGild/Unstable/Type/Comments.hs (hunk 1 above)
Comment (tfausak) [reply source/library/CabalGild/Unstable/Type/Comments.hs]: I did write tests for this, but `after` is always empty so I'm not sure which way this should go. Since it isn't exercised currently, I'm going to go with my suggestion here. It makes more sense for `xs` to "wrap around" `ys`. 

``` hs
concat [ before xs, before ys, after ys, after xs ]
```

**Comment by tfausak** [comment]
Somewhat amusingly, this PR addresses an old comment here: https://github.com/tfausak/cabal-gild/pull/56#discussion_r1511230459

**Comment by tfausak** [comment]
This fixes the problem and doesn't change the formatting for any of the Cabal files for packages that I maintain. Granted, I don't write that many comments in my Cabal files, but it's a good sign regardless.
