### PR TITLE
Throw exception when option is overridden

### LINKED ISSUE #80: Duplicated command line arguments are ignored
Hello, thank you for cabal-gild, it's working great!

Though I had a little usability issue when using it to format multiple cabal files.
I thought cabal-gild would work like fourmolu where you can give it multiple files at once.
However, it seems like it silently ignores duplicated arguments and it only process the last one.

For example, this invocation:

```
$ cabal-gild --io ./lib/lib.cabal --io ./server/server.cabal --io ./client/client.cabal
```

… only format the `client.cabal` file. The other ones are not touched.

Would it makes sense to support this use case, or at least throw an error in that case?

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #80. 

Previously if you passed the same option twice, Gild would silently ignore the first one and use the second one. For example:

``` sh
# cabal-gild -i x -i y
```

That command will use `y` for input and ignore `x`. 

This PR changes the behavior so that Gild will throw an exception in situations like the above. For example:

``` sh
# cabal-gild -i x -i y
overriding option --input (before: x, after: y)
```

### CODE REVIEW

File: source/library/CabalGild/Unstable/Type/Flag.hs [hunk 1]
```diff
@@ -46,43 +50,82 @@ options =
...
+  emitWarnings flgs
   Foldable.traverse_ (Exception.throwM . InvalidOption.fromString) errs
-  Foldable.traverse_ (Exception.throwM . UnknownOption.fromString) opts
   pure flgs
+
+emitWarnings :: (MonadWarn.MonadWarn m) => [Flag] -> m ()
+emitWarnings =
+  let toWarnings o l =
+        fmap (uncurry . flip $ DuplicateOption.DuplicateOption o)
+          . reverse
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Type/Flag.hs:116]: I should refactor this to avoid `reverse`.

**Comment by tfausak** [comment]
Note that this is a change in behavior since previously some places that would throw an exception will now merely emit a warning.

**Comment by tfausak** [comment]
I think it would be better to avoid changing any existing behavior and instead only add new warnings. That way this won't have to be a breaking change, and I can focus on improving the CLI later.

File: source/library/CabalGild/Unstable/Type/Flag.hs (hunk 1 above)
Comment (tfausak) [reply source/library/CabalGild/Unstable/Type/Flag.hs:116]: Turns out this is not worth the trouble. Plus usually the list will have one or two elements here.

**Comment by tfausak** [comment]
I'm now wondering if I should scrap this as well and just throw a warning in this case instead of an error. Not sure why I didn't consider that before.
