### PR TITLE
Fix rendering of conditionals

### LINKED ISSUE #72: Bad conditional formatting
``` cabal
if (impl(ghc >= 9.2)&& impl(ghc < 9.3))
```

There should be a space before `&&`.

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #72.

### CODE REVIEW

**Comment by tfausak** [comment]
This was more involved than you might think at first. I have been trying to lean on `Cabal-syntax` as much as possible. However for conditionals I wasn't able to do that. First of all there are no `Parsec` or `Pretty` instances for them. But even if there were, the `Condition` data type doesn't have a constructor for parentheses, so those would be lost. Also the parsers would have to be "permissive", which they might not be. So that's why I made my own `Condition` and `Variable` types. Everything else followed from that.

File: source/library/CabalGild/Unstable/Extra/Name.hs [hunk 1]
```diff
@@ -21,8 +22,10 @@ isIf :: Fields.Name a -> Bool
 isIf = (== String.toUtf8 "if") . value
 
 -- | Returns true when the name is @"elif"@, false otherwise.
-isElif :: Fields.Name a -> Bool
-isElif = (== String.toUtf8 "elif") . value
+isElif :: CabalSpecVersion.CabalSpecVersion -> Fields.Name a -> Bool
+isElif csv n =
+  csv >= CabalSpecVersion.CabalSpecV2_2
+    && value n == String.toUtf8 "elif"
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Extra/Name.hs:28]: The `elif` section only became a thing with Cabal 2.2. So for versions before that, we no longer try to format it. Hopefully this will help people realize that something is wonky.

File: source/library/CabalGild/Unstable/Type/Condition.hs [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+          [PE.Infix (And <$ Parse.string "&&" <* Parse.spaces) PE.AssocRight],
+          [PE.Infix (Or <$ Parse.string "||" <* Parse.spaces) PE.AssocRight]
+        ]
+  Parse.spaces
+  PE.buildExpressionParser operators $
+    Parsec.unPP
+      ( Parse.choice
+          [ Par <$> Parse.parens (parseCondition parseVariable),
+            Not <$> (Parse.token "!" *> parseCondition parseVariable),
+            Lit <$> Parse.try parseLit,
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Type/Condition.hs:35]: This needed `try` because trying to parse `flag(x)` would fail because the `f` would be taken for `false`, but then it would fail and not back track.

File: source/library/CabalGild/Unstable/Type/Variable.hs [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+
+parseOs :: (Parsec.CabalParsing m) => m System.OS
+parseOs =
+  fmap (System.classifyOS System.Permissive) $
+    Parse.token "os" *> Parse.parens parseIdent
+
+parseIdent :: (Parsec.CabalParsing m) => m String
+parseIdent =
+  let isIdent c = Char.isAlphaNum c || c == '_' || c == '-'
+   in Parse.munch1 isIdent <* Parse.spaces
```
Comment (tfausak) [inline source/library/CabalGild/Unstable/Type/Variable.hs:56]: This is _very_ lenient. The actual parsers in Cabal aren't as forgiving.
